name = "UnicodeExplot"
uuid = "54c6f191-63ce-47fb-b776-fa1aa9e2d4a6"
authors = ["Karl Wessel <karl.wessel@stud.uni-goettingen.de>"]
version = "0.1.0"

[deps]
TextUserInterfaces = "2a09ff82-1be9-11e9-2ab7-19964783a84b"
UnicodePlots = "b8865327-cd53-5732-bb35-84acbb429228"
